🔀 :: (#464) 질문 삭제 API 구현
EntryDSM/Rolls-Royce pull request #465
Opened 2023-03-22 07:00 UTC by jyk1029

close #464

2023-03-22 07:59 UTC, eogus2513 approved these changes

2023-03-22 09:57 UTC, softpeanut requested changes

2023-03-22 09:57 UTC, softpeanut commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/DeleteQnaService.java
> +            throw NotDeleteQnaException.EXCEPTION;
비즈니스 로직상에서 이 예외와 어울리지 않는 것 같아요
작성자가 다를 때에 예외를 던지는 상황인데 `Not delete qna`는 어떤 걸 의미하는지 잘 모르겠어요

2023-03-22 10:06 UTC, jyk1029 commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/DeleteQnaService.java
> +            throw NotDeleteQnaException.EXCEPTION;
그러면 `UnauthorizedDeleteQnaException`는 괜찮을까요?

2023-03-22 13:59 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/exception/NotQnaWriterException.java
> +        super(ErrorCode.NOT_QNA_WRITER);
p3) Class 명 조금 더 생각해보면 좋을 것 같아요.

2023-03-22 13:59 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
> +    NOT_QNA_WRITER(401, "QNA401-0", "Not qna Writer"),
p1) 400이 아니라 다른 코드로 표현한다면 401(UnAuthorized)보다는 403(Forbidden)이 나을 것 같네요

2023-03-22 13:59 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/DeleteQnaService.java
> +DeleteQnaService {
p4) 여기 엔터 정리좀해주세요

2023-03-22 14:43 UTC, syxxn commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/CreateQnaService.java
>                  Qna.builder()
취향 차이일수도 있는데 메소드 안에 메소드 하나 더 넣는 것보다
생성 객체는 따로 빼는 게 더 좋은 것 같아요

아예 메소드로 빼서
public createQna(Request request) {
  return Qna.builder().build();
}
로 해도 좋을듯

2023-03-22 14:43 UTC, syxxn commented on src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
> +    NOT_QNA_WRITER(403, "QNA403-0", "Not qna Writer"),
다른 error code 메시지는 다 문장인데 왜 이건 클래스명 느낌이에요??

2023-03-22 23:35 UTC, jyk1029 commented on src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
> +    NOT_QNA_WRITER(403, "QNA403-0", "Not qna Writer"),
마땅히 생각하는 것이 없어서 계속 고민해보고 있는 중입니다..😢

2023-03-23 02:41 UTC, jyk1029 commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/exception/NotQnaWriterException.java
> +        super(ErrorCode.NOT_QNA_WRITER);
`WriterMisMatchedException`은 어떨까요?

2023-03-26 09:04 UTC, leeseojune53 requested changes

2023-03-26 09:04 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/DeleteQnaService.java
> +        if (!user.equals(qna.getUser())) {
**p1) user.equals(qna.getUser()) 를 사용하였을 때 발생하는 문제가 있을 것 같습니다.**

2023-03-26 13:16 UTC, jyk1029 commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/DeleteQnaService.java
> +        if (!user.equals(qna.getUser())) {
발생하는 문제가 NullPointerException을 말씀하시는 건가요??

2023-03-27 00:23 UTC, softpeanut commented on src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
> +    WRITER_MISMATCHED(403, "QNA403-0", "Writer Mismatched"),
이거 순서가 이상한 것 같은데 에러 코드 정리 좀 해주세요

2023-03-27 13:42 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/DeleteQnaService.java
> +        if (!user.equals(qna.getUser())) {
아닙니다. 다른 부분은 생각되는거 없을까요?

2023-03-28 04:23 UTC, jyk1029 commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/DeleteQnaService.java
> +        if (!user.equals(qna.getUser())) {
현재까지는 아직 생각되는 부분이 없습니다..

2023-03-28 11:26 UTC, jyk1029 commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/DeleteQnaService.java
> +        if (!user.equals(qna.getUser())) {
혹시 hashcode의 문제일까요??

2023-04-03 14:25 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/DeleteQnaService.java
> +        if (!user.equals(qna.getUser())) {
`equals` 이야기였습니다. 재정의하기 번거로우니 id를 이용해서 비교하는게 좋을 것 같습니다.
위 경우와 같이 사용하였을 때 발생할 수 있는 예외적인 부분이 있을 것 같은데 생각나시는것 있을까요?

2023-04-04 13:16 UTC, jyk1029 commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/DeleteQnaService.java
> +        if (!user.equals(qna.getUser())) {
생각나는 게 없는데 무엇인지 알려줄 수 있으신가요? 😢

2023-04-05 23:48 UTC, softpeanut approved these changes

2023-04-10 14:40 UTC, leeseojune53 commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/DeleteQnaService.java
> +        if (!user.equals(qna.getUser())) {
같다고 나오지만, 명확성을 위해서 userId로 비교하는걸 추천드릴게욥 :)

2023-04-10 21:54 UTC, jyk1029 commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/DeleteQnaService.java
> +        if (!user.equals(qna.getUser())) {
넵!🙂

2023-04-20 14:37 UTC, leeseojune53 approved these changes
LGTM

2023-04-21 00:43 UTC, merged