🔀 :: (#483) 비밀번호 변경 API 구현
EntryDSM/Rolls-Royce pull request #484
Opened 2023-03-28 00:35 UTC by lilseongwon

close #483

2023-04-03 08:14 UTC, eogus2513 commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/request/PasswordRequest.java
> +
PasswordRequest가 어떤 의미인지 정확하게 모르겠어요
또 ERD보니깐 name은 5글자로 제한되어 있는데 Validation 옵션 안줘도 되나요?

2023-04-03 09:20 UTC, lilseongwon commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/request/PasswordRequest.java
> +
name은 find용으로 쓸 거라 다른 검증을 하지 않아도 괜찮다고 생각합니다

2023-04-05 23:50 UTC, softpeanut requested changes

2023-04-05 23:50 UTC, softpeanut commented on src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserRepository.java
> +    User findByTelephoneNumberAndName(String telephoneNumber, String name);
Optional로 반환 안하나요?

2023-04-09 14:48 UTC, leeseojune53 approved these changes

2023-04-10 10:43 UTC, softpeanut approved these changes

2023-04-11 04:19 UTC, merged